### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by PallasStreams**

### CODE REVIEW

**Comment by iamvery** [comment]
Why add a license to the bot?

**Comment by PallasStreams** [comment]
More fomality than anything. It's not needed but I figured if anyone ever wanted to base their bot on ours might as well have a license letting them know what they can or cannot do.

**Comment by iamvery** [comment]
Gotcha, ok that’s fine. I tend to wait on a request to do something like this, but no real concerns. Any restrictions from the Apache license that we should be aware of?

**Comment by PallasStreams** [comment]
Not that I'm aware of. Here's a screenshot from GitHub showing what the license does at a high level.
image

Basically lets people fork and do whatever they want with the code but we can't be held liable and we don't provide a warranty on the code if someone runs into issues. So pretty much the only thing we have to worry about is bugs that causes problems for our community.

**Pull request merged**
