### PR TITLE
Add note about notifications and mute to welcome

### PR DESCRIPTION
**Pull request by iamvery**

### CODE REVIEW

**Comment by iamvery** [comment]
:eyes: @tech256/folks

**Comment by chrisbeaman** [comment]
Here's a rewrite of the welcome message that includes a tip about notifications and muting. Feel free to keep, ignore, edit, etc:


Hey @username, welcome to :256:! 

If you haven't done so already, please upload an avatar and fill out your profile. We're a friendly group–we don't bite, promise!–but we are a community that likes to know our neighbors!

There are a lot of channels here that represent different topics (e.g. #code, #testing, #jobs, etc). A lot of silliness goes down in #random. You can see our full list of channels here: https://tech256.slack.com/archives

One thing you’ll want to do is configure your notification settings. Otherwise, Slack will likely send you many more pings and emails than you’re comfortable with! Consider muting channels that you’re less interested in. We’d rather you stick around and be comfortable than leave because you’re overwhelmed with notifications. https://tech256.slack.com/account/notifications 

If you have any questions, reach out to our moderators: @jay, @bryanp, @bmeadows or @mjcarroll. We’re happy to help. Also, please review our Code of Conduct (https://github.com/tech256/CoC). Our goal is to support an open, inclusive North Alabama tech community — please help us make Tech256 a great place for everybody.

**Comment by jay** [comment]
I am not a moderator here, I think you mean @iamvery , can you please change the comment to that

**Comment by iamvery** [comment]
Sorry @jay. Signals getting crossed between Slack usernames and Github. ❤️

**Comment by jay** [comment]
Ok

**Comment by chrisbeaman** [comment]
Sorry about that. Looks like copying and pasting those usernames resulted in notifying those Github names.

**Comment by RandomlyKnighted** [comment]
Yep, and looks like you tagged the wrong bmeadows as well. 

cc: @blmeadows

**Comment by chrisbeaman** [comment]
I didn't write it here, I wrote it in Slack and then pasted it here.

**Comment by RandomlyKnighted** [comment]
Right, I just meant that when you paste it here you also tagged the wrong Britany. I was just trying to keep her in the loop by CC'ing her.

**Pull request merged**
